spring.mvc.view.prefix: /resources/public/jsp/
spring.mvc.view.suffix: .jsp

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO
    org.zen: DEBUG
    org.apache.tiles: DEBUG
  
spring.datasource:
  url: jdbc:h2:mem:zendb
  username: sa
  password: 
  driver-class-name: org.h2.Driver
  

spring.jpa.hibernate.ddl-auto: create-drop
    
application: 
  message: Hello Chris !



