spring.mvc.view.prefix: /resources/public/jsp/
spring.mvc.view.suffix: .jsp

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO
    org.zen: DEBUG
    org.apache.tiles: DEBUG
<<<<<<< HEAD
  
spring.datasource:
  url: jdbc:h2:mem:zendb
  username: sa
  password: 
  driver-class-name: org.h2.Driver
  

spring.jpa.hibernate.ddl-auto: create-drop
=======
>>>>>>> 106b5205c1c0404154c3824a105fae6daac4e16a
    
application: 
  message: Hello Chris !



